POST https://nomnomzerofour.vercel.app/nomfour/register
Content-Type: application/json

{
    "username": "superadmin ",
    "password": "12345"
}

###
POST https://nomnomzerofour.vercel.app/nomfour/day
Content-Type: application/json

{
    "name": "Sabtu"
}

###
POST https://nomnomzerofour.vercel.app/nomfour/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "12345"
}

###
POST https://nomnomzerofour.vercel.app/nomfour/categories
Content-Type: application/json

{
    "name": "Berita"
}

###
GET https://nomnomzerofour.vercel.app/nomfour/days
